"use client"
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "sonner";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { UpdateCartContext } from "./_context/UpdateCartContex";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const outfit = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname();
  const [updateCart, setUpdateCart] = useState(false);
  const showHeader = params=='/sign-in'||params=='/create-account'?false:true;
  return (
    <PayPalScriptProvider options={{ clientId:process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID}}>
        <html lang="en">
            <UpdateCartContext.Provider value={{updateCart, setUpdateCart}}>
                <body className={outfit.className}>
                  {showHeader&&<Header/>}
                  {children}
                  <Toaster/>
                </body>
            </UpdateCartContext.Provider>
        </html>
    </PayPalScriptProvider>
  );
}
